# Generated by Django 4.0.1 on 2022-03-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_title', models.CharField(max_length=200)),
                ('c_code', models.CharField(max_length=200)),
                ('c_hour', models.IntegerField()),
                ('faculty', models.CharField(max_length=200)),
                ('semister', models.CharField(max_length=200)),
            ],
        ),
    ]
